services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: vapp-docker
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"